http:
  http://localhost:{{ .Vars.containerPorts.http }}/health:
    status: 200
command:
  check-user-info:
    exec: id
    exit-status: 0
    stdout:
    - uid={{ .Vars.containerSecurityContext.runAsUser }}
    - /groups=.*{{ .Vars.podSecurityContext.fsGroup }}/
